sample_name = "Friesach"

[[divisions]]
name = "Pedale"
stops = [
  "Untersatz 32'",
  "Contrabass 16'",
  "Subbass 16'",
  "Octavbass 8'",
  "Gedackt 8'",
  "Choralbass 4'",
  "Posaune 32'",
  "Posaune 16'",
  "Trompete 8'"
]

[[divisions]]
name = "Hauptwerk"
stops = [
  "Praestant 16'",
  "Principal 8'",
  "Holzflöte 8'",
  "Röhrflöte 8'",
  "Gambe 8'",
  "Octave 4'",
  "Spitzflöte 4'",
  "Quinte 2 2/3'",
  "Octave 2'",
  "Mixtur major 4-5f. 2 2/3'",
  "Mixtur minor 4f. 1 1/3'",
  "Trompete 16'",
  "Trompete 8'"
]

[[divisions]]
name = "Schwellwerk"
stops = [
  "Bourdon 16'",
  "Principal 8'",
  "Nachthorn Gedackt 8'",
  "Corno dolce 8'",
  "Viola 8'",
  "Vox celeste 8'",
  "Geigenprincipal 4'",
  "Querflöte 4'",
  "Nazard 2 2/3'",
  "Flageolett 2'",
  "Tierce 1 3/5'",
  "Larigot 1 1/3'",
  "Plein Jeu 4-5f. 2'",
  "Scharff 4f. 1'",
  "Trompete harmonique 8'",
  "Hautbois 8'",
  "Clairon 4'"
]
tremolo = true

[[divisions]]
name = "Solo"
stops = [
  "Jubalflote 8'",
  "Trichtflote 4'",
  "Cornet a pavaillon 1-8f. 8'",
  "Trompete en chamade 8'",
  "Englischhorn 8'"
]
tremolo = true

[[couplers]]
name = "I/P"
from_division = "Hauptwerk"
to_division = "Pedal"

[[couplers]]
name = "II/P"
from_division = "Schwellwerk"
to_division = "Pedal"

[[couplers]]
name = "III/P"
from_division = "Solo"
to_division = "Pedal"

[[couplers]]
name = "II/I"
from_division = "Schwellwerk"
to_division = "Hauptwerk"

[[couplers]]
name = "III/I"
from_division = "Solo"
to_division = "Hauptwerk"

[[couplers]]
name = "III/II"
from_division = "Solo"
to_division = "Schwellwerk"